// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using apenew;

#nullable disable

namespace apenew.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250318234844_UpdateDb")]
    partial class UpdateDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("apenew.Models.Assessment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ApplicationID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AssessmentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Justification")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReviewedBy")
                        .HasColumnType("text");

                    b.Property<string>("SolutionDesignImagePath")
                        .HasColumnType("text");

                    b.Property<DateTime?>("StartReviewAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SubmittedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Assessments");
                });

            modelBuilder.Entity("apenew.Models.Capability", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AssessmentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CapabilityName")
                        .HasColumnType("text");

                    b.Property<string>("Checked")
                        .HasColumnType("text");

                    b.Property<string>("Control")
                        .HasColumnType("text");

                    b.Property<string>("Evidence")
                        .HasColumnType("text");

                    b.Property<string>("SubControlID")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AssessmentId");

                    b.ToTable("Capabilities");
                });

            modelBuilder.Entity("apenew.Models.Pin", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AssessmentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CapabilityId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Height")
                        .HasColumnType("double precision");

                    b.Property<double>("Width")
                        .HasColumnType("double precision");

                    b.Property<double>("X")
                        .HasColumnType("double precision");

                    b.Property<double>("Y")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("AssessmentId");

                    b.HasIndex("CapabilityId");

                    b.ToTable("Pins");
                });

            modelBuilder.Entity("apenew.Models.Capability", b =>
                {
                    b.HasOne("apenew.Models.Assessment", "Assessment")
                        .WithMany("Capabilities")
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assessment");
                });

            modelBuilder.Entity("apenew.Models.Pin", b =>
                {
                    b.HasOne("apenew.Models.Assessment", "Assessment")
                        .WithMany("Pins")
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("apenew.Models.Capability", "Capability")
                        .WithMany()
                        .HasForeignKey("CapabilityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Assessment");

                    b.Navigation("Capability");
                });

            modelBuilder.Entity("apenew.Models.Assessment", b =>
                {
                    b.Navigation("Capabilities");

                    b.Navigation("Pins");
                });
#pragma warning restore 612, 618
        }
    }
}
